stages:
    - test
    - package
    - deploy

test:
  image: node:14-alpine
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test:unit -- --coverage
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules
  artifacts:
      reports:
          cobertura: coverage/cobertura-coverage.xml

docker-build-main:
  # Official docker image.
  image: docker:latest
  stage: package
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main

docker-build:
  # Official docker image.
  image: docker:latest
  stage: package
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - main

build-artifacts:
  image: node:14-alpine
  stage: package
  script:
      - npm install
      - npm run build
      - echo "$CI_COMMIT_REF_NAME" > dist/DEPLOY_ID
      - echo "$CI_COMMIT_SHA" >> dist/DEPLOY_ID
      - echo "$CI_JOB_STARTED_AT" >> dist/DEPLOY_ID
  artifacts:
      name: "fundraising-assets-$CI_COMMIT_REF_NAME"
      public: true
      paths:
          - dist
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules

